openapi: "3.0.0"
info:
  title: "Python Sample Data Server"
  description: "An API about the Harry Potter Universe"
  version: "1.0.0"

servers:
  - url: "/api"

components:
  schemas:
    Person:
      type: "object"
      required:
        - last_name
      properties:
        first_name:
          type: "string"
        last_name:
          type: "string"
  parameters:
    last_name:
      name: "last_name"
      description: "Last name of the person to get"
      in: path
      required: True
      schema:
        type: "string"

paths:
  /people:
    get:
      operationId: people.read_all
      tags:
        - People
      summary: "Read the list of people"
      responses:
        200:
          description: "Successfully read the list of people"
    post:
      operationId: people.create
      tags:
        - People
      summary: "Creates a person"
      requestBody:
        description: "person to create"
        required: True
        content:
          application/json:
            schema:
              x-body-name: "person"
              $ref: "#/components/schemas/Person"
      responses:
        201:
          description: "Successfully created person"
  /people/{last_name}:
    get:
      operationId: people.read_one
      tags:
        - People
      summary: "Reads one person"
      parameters:
        - $ref: "#/components/parameters/last_name"
      responses:
        200:
          description: "Successfully read person"
