openapi: "3.0.0"
info:
  title: "Python Sample Data Server"
  description: "An API to mock patient demographic and health record data"
  version: "1.0.0"

servers:
  - url: "/api"

# components:
#   schemas:
#     Person:
#       type: "object"
#       required:
#         - last_name
#       properties:
#         first_name:
#           type: "string"
#         last_name:
#           type: "string"
#   parameters:
#     last_name:
#       name: "last_name"
#       description: "Last name of the person to get"
#       in: path
#       required: True
#       schema:
#         type: "string"

paths:
  /patients:
    get:
      operationId: patients.get_all
      tags:
        - Patients
      summary: "Return a list of mock patients"
      responses:
        200:
          description: "Successfully generated a list of mock patients"

